package:
  name: nodejs
  version: 4.4.1

build:
  number: {{environ.get('GIT_DESCRIBE_NUMBER', 0)}}

source:
  fn: node-v4.4.3-linux-x64.tar.gz [linux64]
  url: https://nodejs.org/dist/v4.4.3/node-v4.4.3-linux-x64.tar.gz [linux64]
  sha256: 28ff2b23a837526ecfea66b0db42d43ec84368949998f2cb26dd742e8988ec1f [linux64]

  fn: node-v4.4.3-darwin-x64.tar.gz [osx]
  url: https://nodejs.org/dist/v4.4.3/node-v4.4.3-darwin-x64.tar.gz [osx]
  sha256: 7cbb9819926d90c9c9f31c3db4c83499a3d9518ad3c7d9915fa4c66d6d5875df [osx]

  fn: node-v4.4.3-x64.msi [win]
  url: https://nodejs.org/dist/v4.4.3/node-v4.4.3-x64.msi [win64]
  sha256: 388197c171805d97746d29b64d1e98c87dca378e70d5e947875327772bb2d560 [win64]

test:
  commands:
    - node --help
    - node --version
    - npm --version

about:
  home: http://nodejs.org/
  license: V8
